apiVersion: v1
kind: Service
metadata:
  name: service-visits
spec:
  selector:
    app: service-visits
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 30003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-visits
spec:
  selector:
    matchLabels:
      app: service-visits
  replicas: 1
  template:
    metadata:
      labels:
        app: service-visits
    spec:
      containers:
        - name: server
          image: nerbivol/service-visits:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8083

---